set echo on;
spool 02_create_database.log;

CREATE DATABASE o112ee
 MAXINSTANCES 8
 MAXDATAFILES 255
 MAXLOGFILES 255
 MAXLOGMEMBERS 4
 MAXLOGHISTORY 255
 DATAFILE '/u02/oradata/o112ee/data/system/system.dbf'
  SIZE 512M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
  EXTENT MANAGEMENT LOCAL
 SYSAUX DATAFILE '/u02/oradata/o112ee/data/system/sysaux.dbf'
  SIZE 1024M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
 UNDO TABLESPACE "UNDOTBS"  DATAFILE '/u02/oradata/o112ee/data/system/undotbs.dbf'
  SIZE 256M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
 DEFAULT TEMPORARY TABLESPACE TEMP TEMPFILE '/u02/oradata/o112ee/data/system/temp.dbf'
  SIZE 256M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
 CHARACTER SET AL32UTF8
 NATIONAL CHARACTER SET AL16UTF16
 LOGFILE GROUP 1 ('/u02/oradata/o112ee/redo/redo01.log') SIZE 256M REUSE,
 GROUP 2  ('/u02/oradata/o112ee/redo/redo02.log') SIZE 256M REUSE,
 GROUP 3  ('/u02/oradata/o112ee/redo/redo03.log') SIZE 256M REUSE
 USER SYS IDENTIFIED BY "CHANGE_ON_INSTALL"
 USER SYSTEM IDENTIFIED BY "MANAGER";

disconnect;
spool off;

exit;
